[project]
name = "web-boardimage"
version = "0.1.0"
description = "An HTTP service that renders chess board images"
readme = "README.md"
authors = [
    { name = "Niklas Fiekas", email = "niklas.fiekas@backscattering.de" },
]
requires-python = ">=3.10"
dependencies = [
    "aiohttp~=3.14.3",
    "chess~=1.11.2",
    "CairoSVG~=2.9.0",
]
